import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  ...compat.config({
    extends: ['next/core-web-vitals', 'next/typescript', 'prettier'],
    rules: {
      // Security: ban raw HTML injection unless a line is explicitly reviewed
      // and annotated with an eslint-disable comment + justification.
      'react/no-danger': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'warn',
    },
  }),
  {
    // Architecture guardrail: forbid importing disallowed persistence / storage
    // layers anywhere in the app (database-free constraint). See Block 1.
    files: ['src/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            { name: '@prisma/client', message: 'No app database. See docs/storage-model.md.' },
            { name: 'prisma', message: 'No app database. See docs/storage-model.md.' },
            { name: 'pg', message: 'No app database. See docs/storage-model.md.' },
            { name: 'mysql2', message: 'No app database. See docs/storage-model.md.' },
            { name: 'redis', message: 'No Redis. See docs/storage-model.md.' },
            { name: 'ioredis', message: 'No Redis. See docs/storage-model.md.' },
            { name: '@vercel/kv', message: 'No Vercel KV. See docs/storage-model.md.' },
            { name: '@vercel/blob', message: 'No Vercel Blob. See docs/storage-model.md.' },
            { name: '@vercel/postgres', message: 'No Vercel Postgres. See docs/storage-model.md.' },
            {
              name: '@aws-sdk/client-s3',
              message: 'No object storage. See docs/storage-model.md.',
            },
            { name: 'firebase', message: 'No Firebase. See docs/storage-model.md.' },
            { name: 'firebase-admin', message: 'No Firebase. See docs/storage-model.md.' },
            { name: '@supabase/supabase-js', message: 'No Supabase. See docs/storage-model.md.' },
            { name: 'idb', message: 'No IndexedDB persistence. See docs/storage-model.md.' },
            { name: 'idb-keyval', message: 'No IndexedDB persistence. See docs/storage-model.md.' },
          ],
        },
      ],
    },
  },
  {
    ignores: [
      'node_modules/**',
      '.next/**',
      'out/**',
      'coverage/**',
      'design-intake/**',
      'playwright-report/**',
      'test-results/**',
      'next-env.d.ts',
      // Auto-generated by the Workflow SDK build — not hand-maintained source.
      'src/app/.well-known/**',
    ],
  },
];

export default eslintConfig;
